version: '3'

services:
  ebidp_backend:
    container_name: ebidp_backend
    command: server
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - "5000:80"
    networks:
      - ebidp_backend
    environment:
      - APP_ENV=develop

  ebidp_celery_worker:
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - redis
    container_name: ebidp_celery_worker
    command: worker
    networks:
      - ebidp_backend
    environment:
      - APP_ENV=develop
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true

  ebidp_rpc_server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: ebidp_rpc_server
    command: zmqrpc
    ports:
      - "5001:4242"
    networks:
      - ebidp_backend

  redis:
    image: redis:4.0
    volumes:
      - ./config/deploy/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - ebidp_backend

networks:
  ebidp_backend: