# Use an official Python runtime as a parent image
FROM python:3.6.5

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
COPY requirements.txt /home/docker/code/
RUN pip install --upgrade pip
RUN pip install -Ur /home/docker/code/requirements.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

# Make port 80 available to the world outside this container
EXPOSE 8080

# Define environment variable
#ENV NAME World
ENV PATH="/usr/bin/docker:${PATH}"

# Run app.py when the container launches
CMD ["python", "import_api.py"]
