version: '3'

services:

  flexbi_backend:
    build:
      context: ..
      dockerfile: Dockerfile-dev
    depends_on:
      - postgres
    container_name: flexbi_backend_dev
    command: idle
    ports:
      - "5000:80"
    volumes:
      - ..:/home/docker/code
      - ../local_data/logs:/var/logs
    environment:
      - ENV=develop
      - DB_ENV_POSTGRES_USER=chenjun
      - DB_ENV_POSTGRES_PASSWORD=123456
      - DB_ENV_POSTGRES_HOST=postgres
      - DB_ENV_POSTGRES_PORT=5432
      - DB_ENV_POSTGRES_DBNAME=flexbi
      - DB_ENV_POSTGRES_DBNAME_TEST=flexbitest
      - MAIL_SERVER=cloud.mysubmail.com
      - MAIL_PORT=25
      - MAIL_USERNAME=11775
      - MAIL_PASSWORD=f2530563c2289d9c6163a5a123ab6d7e
      - MAIL_DEFAULT_SENDER=noreply@yuelemon.com
      - SECRET_KEY=DGMW6pU8x01-mh519JkLsbHOiXZLp4fpUVdHqi58
      - SERVER_NAME=flexceed.com
    networks:
      - flexbi_backend_dev

  postgres:
    image: postgres:9.6.2
    container_name: postgres_dev
    volumes:
      - ../db:/var/lib/postgres/data/pgdata
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
      - PGDATA=/var/lib/postgres/data/pgdata
      - POSTGRES_USER=chenjun
      - POSTGRES_PASSWORD=123456
      - POSTGRES_MULTIPLE_DATABASES=flexbi,flexbitest
    networks:
      - flexbi_backend_dev

networks:
  flexbi_backend_dev:
